import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';
import Header from '../../components/header';


const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>My App</title>
      </Head>
      <div className="container">
      <Header />
        {children}
        {/* Footer component should be here  */}
      </div>
    </>
  );
}


