import { Inter } from 'next/font/google';
//import Head from 'next/head';
import './globals.css';
import Header from '../../components/header/Header.client';

const inter = Inter({ subsets: ['latin'] });

// const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <div
    // className={styles.container}
    >
      {/* <Head> */}
      {/* Metadata can be dynamic, but for simplicity, we'll keep it static here */}
      {/* <title>My App</title>
        <meta name="description" content="Generated by create next app" /> */}
      {/* </Head> */}
      <Header />
      <main
      // className={styles.mainContent}
      >
        {children}
      </main>
      <footer
      // className={styles.footer}
      >
        {/* Footer content */}
      </footer>
    </div>
  );
}
