import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../../components/header';
//  import Client from '../../pages/client';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <Client /> */}
      <div className='container'>{children}</div>
       </body>
    </html>
  );
}

